export const FontFamily = {
    kalamRegular: "Kalam-Regular",
    smallNormalBold: "Inter-Bold",
    inriaSansRegular: "InriaSans-Regular",
    hindJalandhar: "Hind Jalandhar",
    kanitRegular: "Kanit-Regular",
    interRegular: "Inter-Regular",
    outfitMedium: "Outfit-Medium",
    poppinsMedium: "Poppins-Medium",
    poppinsSemiBold: "Poppins-SemiBold",
    poppinsRegular: "Poppins-Regular",
    poppinsBold: "Poppins-Bold",
    mitrMedium: "Mitr-Medium",
    mitrRegular: "Mitr-Regular",
    unifiedDesignDeprecatedFootnote: "SF Pro Text",
    androidFootnote: "Roboto-Regular",
    actorRegular: "Actor-Regular",
  };
  /* font sizes */
  export const FontSize = {
    iOSHeadlineBold_size: 16,
    smallNormalBold_size: 14,
    size_5xl: 24,
    size_29xl: 48,
    size_xl: 20,
    size_7xl: 26,
    unifiedDesignDeprecatedFootnote_size: 12,
    size_16xl: 35,
    size_6xl: 25,
    size_mini: 15,
    size_lg: 18,
    size_2xs: 11,
    androidFootnote_size: 13,
    size_3xl_5: 23,
    size_smi_5: 13,
  };
  /* Colors */
  export const Color = {
    lightWhite: "#fff",
    colorDarkcyan: "#209fa6",
    lightBlack: "#000",
    colorDodgerblue: "#0085ff",
    colorGray_100: "#fcfcfe",
    lightWhiteSnow: "#fcfcfc",
    lightGrey: "#7a7a7a",
    colorGray_200: "#171f1d",
    colorGray_300: "#080707",
    colorGray_400: "rgba(0, 0, 0, 0.41)",
    colorGainsboro_100: "#d9d9d9",
    colorGainsboro_200: "rgba(217, 217, 217, 0.26)",
    colorGainsboro_300: "rgba(217, 217, 217, 0.63)",
    colorWhitesmoke_100: "#f5f5f5",
    lightGreyWhisper: "#ecebeb",
    colorSilver: "rgba(196, 196, 196, 0)",
    colorDarkgray: "#a9a9a9",
    lightAccentRed: "#ff3742",
    colorLightgray: "#d1d5db",
  };
  /* Paddings */
  export const Padding = {
    p_mini: 15,
    p_3xs: 10,
    p_5xs: 8,
    p_8xs: 5,
    p_11xs: 2,
    p_12xs: 1,
    p_7xs: 6,
    p_base: 16,
  };
  /* border radiuses */
  export const Border = {
    br_xl: 20,
    br_11xl: 30,
    br_3xs: 10,
    br_5xs: 8,
    br_99980xl: 99999,
    br_9980xl: 9999,
    br_lg: 18,
    br_base: 16,
    br_8xs_6: 5,
    br_81xl: 100,
  };
  